spring:
  application:
    name: movie-catalog-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      connect-timeout: 2s
      timeout: 2s

  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: false
      key-prefix: "movie-catalog::"
      use-key-prefix: true

  cloud:
    openfeign:
      client:
        config:
          tmdbClient:
            connect-timeout: 2000
            read-timeout: 5000
            logger-level: basic

tmdb:
  base-url: ${TMDB_BASE_URL:https://api.themoviedb.org/3}
  access-token: ${TMDB_ACCESS_TOKEN:}
  default-language: ${TMDB_DEFAULT_LANGUAGE:en-US}
  default-region: ${TMDB_DEFAULT_REGION:US}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true