spring:
  application:
    name: movie-catalog-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      connect-timeout: 2s
      timeout: 2s

  cache:
    type: redis

  cloud:
    openfeign:
      client:
        config:
          tmdbClient:
            connect-timeout: 2000
            read-timeout: 5000
            logger-level: basic

catalog:
  cache:
    trending-ttl: ${CATALOG_CACHE_TRENDING_TTL:15m}
    movie-detail-ttl: ${CATALOG_CACHE_MOVIE_DETAIL_TTL:6h}

tmdb:
  base-url: ${TMDB_BASE_URL:https://api.themoviedb.org/3}
  access-token: ${TMDB_ACCESS_TOKEN:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:false}
